import { StatusBadge } from "@/components/ui/status-badge";

import { createColumnHelper } from "@tanstack/react-table";
import { format } from "date-fns";
import { Edit, Trash2 } from "lucide-react";

const formatDate = (dateString: string | null) => {
	if (!dateString) return "Not set";
	try {
		return format(new Date(dateString), "MMM dd, yyyy HH:mm");
	} catch {
		return "Invalid date";
	}
};

export const createSendingToolLeadListColumns = () => {
	const listColumnHelper = createColumnHelper<any>();
	return [
		// Campaign Name
		listColumnHelper.accessor("campaign.name", {
			header: "Campaign",
			cell: (info) => info.getValue() || "Unknown Campaign",
		}),

		// Format
		listColumnHelper.accessor("format", {
			header: "Format",
			cell: (info) => <StatusBadge>{info.getValue() || "N/A"}</StatusBadge>,
		}),

		// Row Count
		listColumnHelper.accessor("row_count", {
			header: "Rows",
			cell: (info) => info.getValue() ?? 0,
		}),

		// Generated By
		listColumnHelper.accessor("generated_by", {
			header: "Generated By",
			cell: (info) => info.getValue() || "System",
		}),

		// Generated At
		listColumnHelper.accessor("generated_at", {
			header: "Generated",
			cell: (info) => formatDate(info.getValue()),
		}),

		// File URL
		listColumnHelper.accessor("file_url", {
			header: "File",
			cell: (info) => {
				const url = info.getValue();
				if (!url) return "No file";
				return (
					<a
						href={url}
						target="_blank"
						rel="noopener noreferrer"
						className="text-primary hover:underline"
					>
						Download
					</a>
				);
			},
		}),
	];
};

export const createSendingToolLeadListRowActions = (
	setDeleteModal: any,
	setEditModal: any,
) => [
	{
		label: "Edit",
		icon: Edit,
		onClick: (list: any) => {
			setEditModal({
				isOpen: true,
				type: "sending_tool_lead_list",
				data: list,
			});
		},
	},
	{
		label: "Delete",
		icon: Trash2,
		variant: "destructive" as const,
		onClick: (list: any) => {
			setDeleteModal({
				isOpen: true,
				type: "sending_tool_lead_list",
				id: list.id,
				title: `Delete sending tool list for ${list.campaign?.name || "Unknown"}`,
			});
		},
	},
];
