import { StatusBadge } from "@/components/ui/status-badge";

import { createColumnHelper } from "@tanstack/react-table";
import { format } from "date-fns";
import { Edit, Trash2 } from "lucide-react";

const formatDate = (dateString: string | null) => {
	if (!dateString) return "Not set";
	try {
		return format(new Date(dateString), "MMM dd, yyyy HH:mm");
	} catch {
		return "Invalid date";
	}
};

export const createSendingToolLeadListColumns = (options?: {
	hideCampaign?: boolean;
}) => {
	const listColumnHelper = createColumnHelper<any>();
	const columns = [];

	// Campaign Name (conditionally added)
	if (!options?.hideCampaign) {
		columns.push(
			listColumnHelper.accessor("campaign.name", {
				header: "Campaign",
				cell: (info) => info.getValue() || "Unknown Campaign",
			}),
		);
	}

	// Format
	columns.push(
		listColumnHelper.accessor("format", {
			header: "Format",
			cell: (info) => <StatusBadge>{info.getValue() || "N/A"}</StatusBadge>,
		}),
	);

	// Row Count
	columns.push(
		listColumnHelper.accessor("row_count", {
			header: "Rows",
			cell: (info) => info.getValue() ?? 0,
		}),
	);

	// Generated By
	columns.push(
		listColumnHelper.accessor("generated_by_user", {
			header: "Generated By",
			cell: (info) => {
				const user = info.getValue() as any;
				if (!user) return "System";
				const fullName = [user.first_name, user.last_name]
					.filter(Boolean)
					.join(" ");
				return fullName || user.email || "Unknown";
			},
		}),
	);

	// Generated At
	columns.push(
		listColumnHelper.accessor("generated_at", {
			header: "Generated At",
			cell: (info) => formatDate(info.getValue()),
		}),
	);

	// File URL
	columns.push(
		listColumnHelper.accessor("file_url", {
			header: "File",
			cell: (info) => {
				const url = info.getValue();
				if (!url) return "No file";
				return (
					<a
						href={url}
						target="_blank"
						rel="noopener noreferrer"
						className="text-primary hover:underline"
					>
						Download
					</a>
				);
			},
		}),
	);

	return columns;
};

export const createSendingToolLeadListRowActions = (
	setDeleteModal: any,
	setEditModal: any,
) => [
	{
		label: "Edit",
		icon: Edit,
		onClick: (list: any) => {
			setEditModal({
				isOpen: true,
				type: "sending_tool_lead_list",
				data: list,
			});
		},
	},
	{
		label: "Delete",
		icon: Trash2,
		variant: "destructive" as const,
		onClick: (list: any) => {
			setDeleteModal({
				isOpen: true,
				type: "sending_tool_lead_list",
				id: list.id,
				title: `Delete sending tool list for ${list.campaign?.name || "Unknown"}`,
			});
		},
	},
];
